version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
